name: skynet
favicon: null
layout_spectrum: 0.23445
typography_spectrum: 0.471846
title: Skynet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020305'
    - '#167299'
    - '#5bb7de'
    - '#014c6c'
    - '#b4e8fe'
  brandStrength: 1
  lightness: 0.679054
  saturation: 0.849099
  rhythmicContrast: 0.243243
purpose:
  - name: null
    item: null
    url: null
