name: skynet
favicon: null
layout_spectrum: 0.804054
typography_spectrum: 0.471846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5103660-10
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.243243
purpose:
  - name: null
    item: null
    url: null
