analytics: {}
color:
  brandColors: []
  brandStrength: 0.660961
  lightness: 0
  rhythmicContrast: 0.243243
  saturation: 0.849099
cta: {}
layout_spectrum: 0.804054
name: skynet
opengraph: {}
purpose: {}
typography_spectrum: 0.471846
